// countryCodes.js

export const countryCodes = [
  { countryName: "Antigua and Barbuda", flagEmoji: "🇦🇬", code: "+1", countryCode: "AG" },
  { countryName: "Argentina", flagEmoji: "🇦🇷", code: "+54", countryCode: "AR" },
  { countryName: "Aruba", flagEmoji: "🇦🇼", code: "+297", countryCode: "AW" },
  { countryName: "Australia", flagEmoji: "🇦🇺", code: "+61", countryCode: "AU" },
  { countryName: "Austria", flagEmoji: "🇦🇹", code: "+43", countryCode: "AT" },
  { countryName: "Bahamas", flagEmoji: "🇧🇸", code: "+1", countryCode: "BS" },
  { countryName: "Barbados", flagEmoji: "🇧🇧", code: "+1", countryCode: "BB" },
  { countryName: "Belgium", flagEmoji: "🇧🇪", code: "+32", countryCode: "BE" },
  { countryName: "Brazil", flagEmoji: "🇧🇷", code: "+55", countryCode: "BR" },
  { countryName: "Brunei", flagEmoji: "🇧🇳", code: "+673", countryCode: "BN" },
  { countryName: "Canada", flagEmoji: "🇨🇦", code: "+1", countryCode: "CA" },
  { countryName: "Cayman Islands", flagEmoji: "🇰🇾", code: "+1", countryCode: "KY" },
  { countryName: "Chile", flagEmoji: "🇨🇱", code: "+56", countryCode: "CL" },
  { countryName: "Colombia", flagEmoji: "🇨🇴", code: "+57", countryCode: "CO" },
  { countryName: "Costa Rica", flagEmoji: "🇨🇷", code: "+506", countryCode: "CR" },
  { countryName: "Cuba", flagEmoji: "🇨🇺", code: "+53", countryCode: "CU" },
  { countryName: "Czech Republic", flagEmoji: "🇨🇿", code: "+420", countryCode: "CZ" },
  { countryName: "Denmark", flagEmoji: "🇩🇰", code: "+45", countryCode: "DK" },
  { countryName: "Dominican Republic", flagEmoji: "🇩🇴", code: "+1", countryCode: "DO" },
  { countryName: "Egypt", flagEmoji: "🇪🇬", code: "+20", countryCode: "EG" },
  { countryName: "El Salvador", flagEmoji: "🇸🇻", code: "+503", countryCode: "SV" },
  { countryName: "Finland", flagEmoji: "🇫🇮", code: "+358", countryCode: "FI" },
  { countryName: "France", flagEmoji: "🇫🇷", code: "+33", countryCode: "FR" },
  { countryName: "Germany", flagEmoji: "🇩🇪", code: "+49", countryCode: "DE" },
  { countryName: "Great Britain", flagEmoji: "🇬🇧", code: "+44", countryCode: "GB" },
  { countryName: "Greece", flagEmoji: "🇬🇷", code: "+30", countryCode: "GR" },
  { countryName: "Grenada", flagEmoji: "🇬🇩", code: "+1", countryCode: "GD" },
  { countryName: "Guatemala", flagEmoji: "🇬🇹", code: "+502", countryCode: "GT" },
  { countryName: "Guyana", flagEmoji: "🇬🇾", code: "+592", countryCode: "GY" },
  { countryName: "Honduras", flagEmoji: "🇭🇳", code: "+504", countryCode: "HN" },
  { countryName: "Hong Kong", flagEmoji: "🇭🇰", code: "+852", countryCode: "HK" },
  { countryName: "Hungary", flagEmoji: "🇭🇺", code: "+36", countryCode: "HU" },
  { countryName: "India", flagEmoji: "🇮🇳", code: "+91", countryCode: "IN" },
  { countryName: "Ireland", flagEmoji: "🇮🇪", code: "+353", countryCode: "IE" },
  { countryName: "Italy", flagEmoji: "🇮🇹", code: "+39", countryCode: "IT" },
  { countryName: "Jamaica", flagEmoji: "🇯🇲", code: "+1", countryCode: "JM" },
  { countryName: "Japan", flagEmoji: "🇯🇵", code: "+81", countryCode: "JP" },
  { countryName: "Malaysia", flagEmoji: "🇲🇾", code: "+60", countryCode: "MY" },
  { countryName: "Mexico", flagEmoji: "🇲🇽", code: "+52", countryCode: "MX" },
  { countryName: "Netherlands", flagEmoji: "🇳🇱", code: "+31", countryCode: "NL" },
  { countryName: "New Zealand", flagEmoji: "🇳🇿", code: "+64", countryCode: "NZ" },
  { countryName: "Nicaragua", flagEmoji: "🇳🇮", code: "+505", countryCode: "NI" },
  { countryName: "Norway", flagEmoji: "🇳🇴", code: "+47", countryCode: "NO" },
  { countryName: "Panama", flagEmoji: "🇵🇦", code: "+507", countryCode: "PA" },
  { countryName: "Paraguay", flagEmoji: "🇵🇾", code: "+595", countryCode: "PY" },
  { countryName: "Peru", flagEmoji: "🇵🇪", code: "+51", countryCode: "PE" },
  { countryName: "Philippines", flagEmoji: "🇵🇭", code: "+63", countryCode: "PH" },
  { countryName: "Poland", flagEmoji: "🇵🇱", code: "+48", countryCode: "PL" },
  { countryName: "Portugal", flagEmoji: "🇵🇹", code: "+351", countryCode: "PT" },
  { countryName: "Puerto Rico", flagEmoji: "🇵🇷", code: "+1", countryCode: "PR" },
  { countryName: "Romania", flagEmoji: "🇷🇴", code: "+40", countryCode: "RO" },
  { countryName: "Serbia", flagEmoji: "🇷🇸", code: "+381", countryCode: "RS" },
  { countryName: "Singapore", flagEmoji: "🇸🇬", code: "+65", countryCode: "SG" },
  { countryName: "South Africa", flagEmoji: "🇿🇦", code: "+27", countryCode: "ZA" },
  { countryName: "South Korea", flagEmoji: "🇰🇷", code: "+82", countryCode: "KR" },
  { countryName: "Spain", flagEmoji: "🇪🇸", code: "+34", countryCode: "ES" },
  { countryName: "Sweden", flagEmoji: "🇸🇪", code: "+46", countryCode: "SE" },
  { countryName: "Switzerland", flagEmoji: "🇨🇭", code: "+41", countryCode: "CH" },
  { countryName: "Taiwan", flagEmoji: "🇹🇼", code: "+886", countryCode: "TW" },
  { countryName: "Thailand", flagEmoji: "🇹🇭", code: "+66", countryCode: "TH" },
  { countryName: "Turkey", flagEmoji: "🇹🇷", code: "+90", countryCode: "TR" },
  { countryName: "United Arab Emirates", flagEmoji: "🇦🇪", code: "+971", countryCode: "AE" },
  { countryName: "United States", flagEmoji: "🇺🇸", code: "+1", countryCode: "US" },
  { countryName: "Uruguay", flagEmoji: "🇺🇾", code: "+598", countryCode: "UY" },
  { countryName: "Venezuela", flagEmoji: "🇻🇪", code: "+58", countryCode: "VE" },
  { countryName: "Vietnam", flagEmoji: "🇻🇳", code: "+84", countryCode: "VN" }
];